/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const $axios: typeof import('axios')['default']
  const $store: typeof import('@/store')['default']
  const $tool: typeof import('@/utils/tool')['default']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const $message: typeof import('element-plus')['ElMessage']
  const $notify: typeof import('element-plus')['ElNotification']
  const $msgbox: typeof import('element-plus')['ElMessageBox']
  const $messageBox: typeof import('element-plus')['ElMessageBox']
  const $alert: typeof import('element-plus')['ElMessageBox']['alert']
  const $confirm: typeof import('element-plus')['ElMessageBox']['confirm']
  const $prompt: typeof import('element-plus')['ElMessageBox']['prompt']
  const $loading: typeof import('element-plus')['ElLoadingService']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const useLink: typeof import('vue-router')['useLink']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
}
