// element-plus 按需引入
import {
  ElButton,
  ElMessage,
  ElSubMenu,
  ElScrollbar,
  ElForm,
  ElFormItem,
  ElInput,
  ElInputNumber,
  ElCheckbox,
  ElCheckboxGroup,
  ElDropdown,
  ElDropdownMenu,
  ElDropdownItem,
  ElPopper,
  ElPopover,
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElTable,
  ElTableColumn,
  ElRadioGroup,
  ElRadioButton,
  ElDatePicker,
  ElSelect,
  ElOption,
  ElTooltip,
  ElSwitch,
  ElLoading
} from 'element-plus';

const ElComponents = [
  ElButton,
  ElSubMenu,
  ElScrollbar,
  ElForm,
  ElFormItem,
  ElInput,
  ElInputNumber,
  ElCheckbox,
  ElCheckboxGroup,
  ElDropdown,
  ElDropdownMenu,
  ElDropdownItem,
  ElPopper,
  ElPopover,
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElTable,
  ElTableColumn,
  ElRadioGroup,
  ElRadioButton,
  ElDatePicker,
  ElSelect,
  ElOption,
  ElTooltip,
  ElSwitch
];

const ElPlugins = [ElMessage, ElLoading];

export { ElComponents, ElPlugins };
